version: '3.7'

services:
  blazorapp:
    image: ${DOCKER_REGISTRY-}blazorapp
    build:
      context: .
      dockerfile: BlazorApp/BlazorApp/Dockerfile
    networks:
      - DcltNet  
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels:
        - traefik.enable=1
        - traefik.http.routers.blazorapp.rule=Host(`blazorapp.dclt.com.br`)
        - traefik.http.routers.blazorapp.entrypoints=websecure
        - traefik.http.routers.blazorapp.priority=1
        - traefik.http.routers.blazorapp.tls.certresolver=letsencryptresolver
        - traefik.http.routers.blazorapp.service=blazorapp
        - traefik.http.services.blazorapp.loadbalancer.server.port=8080
        - traefik.http.services.blazorapp.loadbalancer.passHostHeader=1

networks:
  DcltNet: 
    external: true
    name: DcltNet 